### ISSUE TITLE
Multiple Select Field Boundary Overflow when many options are chosen

### ISSUE THREAD

**Issue by zach1king** [apalfrey/select2-bootstrap-5-theme#1]
**Environment**
OS: Windows 10
Browser: Chrome v88.0.4324.182
Tested Version: 1.0.0

**Screenshot**
![image](https://user-images.githubusercontent.com/27044184/109411366-8ff69500-79dc-11eb-90a5-7df5fc1da2a0.png)

**Expected result**
When many options are chosen, the options should not exceed the boundary of the field. Instead, those overflown should be on the new line. Moreover, the blinking text cursor should appear right next to the last field.

**Actual result**
Options break through the boundary. The blinking text cursor is on the new line.

**Comment by apalfrey** [comment]
Must have missed that! Sorry about that, I'm working on a bugfix for a couple other things so I'll get that sorted and add it to v1.0.1

Thanks for letting me know!
