### ISSUE TITLE
Change background of select DOM when value selected

### ISSUE THREAD

**Issue by martinbarilik** [apalfrey/select2-bootstrap-5-theme#17]
This used to work with bootstrap4 theme

```
.select2-selection__rendered[title] {
	background-color: #D9FFC7;
}
```

Any change we can do this with bootstrap-5 theme ? I only want to set the color if option:selected is present, if not defaault white select2 is shown

**Comment by apalfrey** [comment]
@martinbarilik I'll have a look into this, would you mind letting me know a couple things?

- Which version of Select2 are you using, 4.0.x or 4.1.x?
- Are you using placeholders with Select2?
- Is the allowClear parameter set to `true`?

Thanks

**Comment by martinbarilik** [comment]
select2 ver. 4.2 with placeholders

allowClear is false and true - i use the style for both

**Comment by apalfrey** [comment]
So, Select2 has changed some functionality in v4.1. Whenever a placeholder is used, the placeholder is set as the title for some reason now.

When using clearable fields, you're able to use the following snippet to color the field;
```css
.select2-selection--clearable {
    background-color: #D9FFC7!important;
}
```

However, this doesn't work when fields aren't clearable. I changed the way padding was applied in order to try better fit the styling of Bootstrap 5 select fields with their custom arrows.

Select2 DOES have events that can be used, and this seems to work;

CSS
```css
.select2-selection--selected {
    background-color: #D9FFC7!important;
}
```

JS
```js
$( "select" ).on( "select2:select", function( e ) {
    $( this ).next().find( ".select2-selection" ).addClass( "select2-selection--selected" );
} );
$( "select" ).on( "select2:unselect", function( e ) {
    var selection = $( this ).next().find( ".select2-selection" );
    var rendered = selection.children( ".select2-selection__rendered" );

    if ( rendered.get( 0 ).nodeName.toLowerCase() == "ul" && rendered.children().length > 0 ) {
        return;
    }

    $( this ).next().find( ".select2-selection" ).removeClass( "select2-selection--selected" );
} );
```

Could you give this a go and let me know how it works?

**Comment by martinbarilik** [comment]
It works partially. If you've got a select which is not deselectable, you need to change the value for styles to be applied ( because the JS is doing the job )

I am going to contact select2 support for this to be resolved. Maybe it's not supposed to work like that with the title on nonselected selects. 

We'll see.

**Comment by apalfrey** [comment]
Ahh yeah, completely missed that part! Yeah, seems like they might have more know how on how this might be able to work.

I'll keep it open for now so you can update this when they get back to you

**Comment by martinbarilik** [comment]
The best solution i came up with is here

https://jsfiddle.net/k3xncz6h/8/

By the looks of it, it was a bug in 4.0.x, they have fixed it. It's not an option anymore to catch the title and i don't think there is option without javascript. 

You can close it now :)

**Comment by apalfrey** [comment]
Ah, well that's a shame, glad you found a solution though!

I'll go ahead and close now then
