### ISSUE TITLE
Bottom border disappears with validated inputs

### ISSUE THREAD

**Issue by tagliala** [apalfrey/select2-bootstrap-5-theme#18]
Hi,

terrific job here! 👏🏼👏🏼👏🏼

Just found this issue:

![image](https://user-images.githubusercontent.com/556268/111795873-e5c9a900-88c7-11eb-8ee3-b84c4aa4bf00.png)

How to replicate:
- https://apalfrey.github.io/select2-bootstrap-5-theme/4.0/
- Click twice on `Validation > With .was-validated` example

The reason is that the transparent top/bottom border rule should only be applied if the container is open

**Comment by apalfrey** [comment]
Thanks a lot for this! Sorry it took me so long to respond, I've been a bit busy with some work projects.

You're absolutely right, it shouldn't be applied to focus. I'm getting that sorted now and it'll be available in the next update!

**Comment by apalfrey** [comment]
New release v1.2.0 is out now!
