### ISSUE TITLE
Option disabled attr

### ISSUE THREAD

**Issue by mahlenko** [apalfrey/select2-bootstrap-5-theme#20]
Hi, the options marked with the disabled attribute are not stylized in any way. I made this option, it would be nice if your package had such support.

```
.select2-results__option {
    &[aria-disabled] {
        @extend .text-secondary;
        opacity: .5;
    }
}
```

**Comment by apalfrey** [comment]
This has already been added in v1.1.1: https://github.com/apalfrey/select2-bootstrap-5-theme/releases/tag/1.1.1

If you look at the examples, you should be able to see the styling on the dropdowns (see image below)

![image](https://user-images.githubusercontent.com/10856428/118029964-9a2dfb80-b35c-11eb-9db2-1b68ab40d108.png)
