### ISSUE TITLE
scrolls appear in each of the option group

### ISSUE THREAD

**Issue by aimengda** [apalfrey/select2-bootstrap-5-theme#36]
if we build select2 on a large dataset, we can see scroll bar in each of the option group.

Possible solution: change 
```
.select2-container--bootstrap-5 .select2-dropdown .select2-results__options {
    max-height: 15rem;
    overflow-y: auto;
}
```
into this:
```
.select2-results > .select2-results__options {
    overflow-y: auto;
    max-height: 40vh;
}
```

**Comment by apalfrey** [comment]
@aimengda Could you provide us with an example so we can see what's going on using something like CodePen or JSFiddle?

**Comment by rhssiiy** [comment]
Faced the same issue. Here is minimal working demo: https://codepen.io/rhssiiy/pen/GRmQmKZ

**Comment by apalfrey** [comment]
Ahh, I see the issue! Turns out `.select2-results__options` is used for the whole options dropdown and any groups within it. I'll get this sorted soon, in the meantime here's a little workaround that should work:

```
.select2-container--bootstrap-5 .select2-dropdown .select2-results__options {
  max-height: none;
}

.select2-container--bootstrap-5 .select2-dropdown .select2-results__options:not(.select2-results__options--nested) {
  max-height: 15rem;
}
```

**Comment by rhssiiy** [comment]
Thank you!
