### ISSUE TITLE
how can I use it in Vue Js

### ISSUE THREAD

**Issue by abbasmashaddy72** [apalfrey/select2-bootstrap-5-theme#52]
Use of Vue JS with HTML and script of Vue

please help me out

@apalfrey

**Comment by apalfrey** [comment]
I've not got experience with Vue.js, but I'm assuming you should just be able to either add it to your SCSS file as an import or add it in a link tag, using the jsdelivr link in the readme as the href?

Or are you asking how to use select2 as a whole in Vue.js? If so you'd need to ask them over on their repo: https://github.com/select2/select2

This project is just to style their library to match with Bootstrap 5

**Comment by abbasmashaddy72** [comment]
Thanks Brother
