### ISSUE TITLE
select2 on modal window

### ISSUE THREAD

**Issue by jamesRUS52** [apalfrey/select2-bootstrap-5-theme#61]
Hello

I can input text to search field when select2 in modal window.
Search field is not focused

**Comment by njones57** [comment]
This is a known issue that is documented on the Select2 site https://select2.org/troubleshooting/common-problems#select2-does-not-function-properly-when-i-use-it-inside-a-bootst

**Comment by apalfrey** [comment]
Wasn't aware this was even an issue with select2, it's not often I put a select field in a modal!

There may be a workaround, however I'll put a fix in for the next release that gives the field a z-index higher than the modal
