### ISSUE TITLE
input not focus on mobile (iphone)

### ISSUE THREAD

**Issue by Boinik** [apalfrey/select2-bootstrap-5-theme#66]
input not focus on mobile (iphone)
https://prnt.sc/ZvUTwGtvGzSj

**Comment by apalfrey** [comment]
Not sure what you mean as I see the input in the dropdown is in focus...

Do you mean the dropdown doesn't have a box shadow around it? If so, that's something we're aware of and are trying to figure out a fix to, see #55 

Please let us know if this is the case so we can close the issue as duplicate

**Comment by Boinik** [comment]
> Not sure what you mean as I see the input in the dropdown is in focus...
> 
> Do you mean the dropdown doesn't have a box shadow around it? If so, that's something we're aware of and are trying to figure out a fix to, see #55
> 
> Please let us know if this is the case so we can close the issue as duplicate

if I press the select I do not open the keyboard on the phone. I need to make the second click on the selected selection and only then I can start entering text. This is very inconvenient
https://prnt.sc/ngLvi4z2VVW6

I think it should work like here https://select2.github.io/select2-bootstrap-theme/

Thank you for your interest

**Comment by dimaloop** [comment]
Maybe its a relative to issue #38 
Try to downgrade jquery to 3.5.1

**Comment by apalfrey** [comment]
Sorry for the delay. Yeah, it sounds like it's either an issue with jQuery 3.6 or an issue with Select2 as this is to do with functionality, not styling. Might be best to check in with Select2. Hope you figure it out!
